pull_request_rules:
  - name: Automerge
    conditions:
      - base=main
      - label="Ready to merge"
      - "#review-threads-unresolved=0"
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge
