#TODO this needs to be here (project root) due to HLS: https://github.com/haskell/haskell-language-server/issues/1260

# We need to disable HLint in Test.hs, since HLS runs it over the processed source, which is unsurprisingly unidiomatic.
#TODO
    # It'd be simpler to just disable these via a comment in the source file.
    # The preferred form is `{- HLINT ignore -}`, but these aren't picked up when using HLint via HLS.
    # See https://github.com/haskell/haskell-language-server/issues/638.
    # The form `{-# ANN module ("HLint: ignore" :: String) #-}` is picked up, but interferes with tasty-discover.
#TODO
    # This affects all Main modules, when we only want to target the one in the test suite.
- ignore:
    name: "Evaluate"
    within: Main
- ignore:
    name: "Use let"
    within: Main
- warn:
    name: "Use explicit module export list"
- warn:
    name: "Use module export list"
- ignore:
    name: "Use explicit module export list"
    within: Tests.**
- ignore:
    name: "Use module export list"
    within: Tests.**
