- warn:
    name: "Use explicit module export list"
- warn:
    name: "Use module export list"
- ignore:
    name: "Use explicit module export list"
    within: Tests.**
- ignore:
    name: "Use module export list"
    within: Tests.**

- warn:
    lhs: anyOf o (== x)
    rhs: elemOf o x
    name: "Use elemOf"
- warn:
    lhs: noneOf o (== x)
    rhs: notElemOf o x
    name: "Use notElemOf"
