# NOTE:
#
# Most commands assume you're running this from the top-level `nix
# develop` shell.

MAKE := $(MAKE) -f Makefile.wasm32

CABAL = wasm32-wasi-cabal

build:	configure discover-tests
	$(CABAL) build all

configure:
	$(CABAL) configure all

test-targets = discover-tests test

$(test-targets):
	$(MAKE) -C primer $@
	$(MAKE) -C primer-api $@

update:
	$(CABAL) update

clean:
	$(CABAL) clean

.PHONY: build configure $(test-targets) update clean
