agents:
  queue: "nix-eval"

steps:
  - command: nix flake archive .#
    label: ":nixos: Archive Nix flake inputs"
    agents:
      queue: "nix-build"

  - command: nix-buildkite
    label: ":nixos: :buildkite:"
    plugins:
      - hackworthltd/nix#v2.2.0:
          expr: ".#hydraJobs"
          use-nix-build: "true"
          attr-prefix: ".#hydraJobs."
          nix-eval-jobs-args: --workers 4 --max-memory-size 4GiB --flake --force-recurse
          agent-tags: queue=nix-build,os=linux
          darwin-step-agent-tags: os=darwin

  - wait

  - label: ":nixos: :linux: Cache the Nix shell"
    command: |
      nix develop --print-build-logs --profile /tmp/hacknix --command echo "done"
    agents:
      queue: "nix-build"

  - label: ":nixos: :macos: Cache the Nix shell"
    command: |
      nix develop --print-build-logs --profile /tmp/hacknix --command echo "done"
    agents:
      queue: "nix-build"
      os: "darwin"
