agents:
  private: "true"

steps:
  - command: nix-buildkite
    label: ":nixos: :buildkite:"
    plugins:
      - hackworthltd/nix-buildkite#hackworthltd-v4:
          file: ci.nix
          post-build-hook:
            /run/current-system/sw/bin/buildkite-private-post-build-hook
