agents:
  os: "linux"

steps:
  - command: nix-buildkite
    label: ":nixos: :buildkite:"
    plugins:
      - circuithub/nix-buildkite:
          file: ci.nix

  - label: ":nixos: Archive Nix flake inputs"
    command: nix flake archive .#

  - wait

  - label: ":nixos: :linux: Cache the Nix shell"
    command: |
      nix develop --print-build-logs --profile /tmp/primer --command echo "done"
  - label: ":nixos: :macos: Cache the Nix shell"
    command: |
      nix develop --print-build-logs --profile /tmp/primer --command echo "done"
    agents:
      os: "darwin"

  - wait

  - label: ":linux: Check haskell-language-server"
    command: |
      nix develop --command haskell-language-server
  - label: ":macos: Check haskell-language-server"
    command: |
      nix develop --command haskell-language-server
    agents:
      os: "darwin"
