agents:
  private: "true"
  os: "linux"

steps:
  - command: nix-buildkite
    label: ":nixos: :buildkite: Build required CI jobs"
    plugins:
      - hackworthltd/nix-buildkite#hackworthltd-v10:
          file: ci.nix

  - label: ":nixos: Archive Nix flake inputs"
    command: nix flake archive .#

  - wait

  - label: ":nixos: :linux: Cache the Nix shell"
    command: |
      nix develop --print-build-logs --profile /tmp/primer --command echo "done"

  - label: ":nixos: :macos: Cache the Nix shell"
    command: |
      nix develop --print-build-logs --profile /tmp/primer --command echo "done"
    agents:
      os: "darwin"

  - label: ":nixos: :buildkite: :stopwatch: Run benchmarks"
    command: nix-buildkite
    agents:
      private: "benchmarking"
    plugins:
      - hackworthltd/nix-buildkite#hackworthltd-v10:
          file: ci-benchmarks.nix
          agent-tags: "private=benchmarking"
