agents:
  queue: "nix-build"
  os: "linux"

steps:
  - label: ":haskell: :linux: Primer Wasm targets"
    command: |
      nix develop .#wasm --print-build-logs --command make -f Makefile.wasm32 update
      nix develop .#wasm --print-build-logs --command make -f Makefile.wasm32
      nix develop .#wasm --print-build-logs --command make -f Makefile.wasm32 test
