# Note: because they take so much time to run, we only run the Primer
# Wasm tests when one of these conditions is true:
#
# 1. The PR has hit the merge queue.
# 2. The PR has the "Run Wasm tests" label.

agents:
  queue: "nix-build"
  os: "linux"

steps:
  # Note: only one of these should run during any given build.
  # Unfortunately, Buildkite doesn't support if-else conditionals, so
  # this gets a bit tricky.

  - label: ":haskell: :linux: Primer Wasm tests"
    if: |
      build.branch =~ /^gh-readonly-queue\// ||
      build.pull_request.labels includes "Run Wasm tests"
    command: |
      nix develop .#wasm --print-build-logs --command make -f Makefile.wasm32 update
      nix develop .#wasm --print-build-logs --command make -f Makefile.wasm32 frontend-prod
      nix develop .#wasm --print-build-logs --command make -f Makefile.wasm32 test

  - label: ":haskell: :linux: Primer Wasm build"
    if: |
      build.branch !~ /^gh-readonly-queue\// &&
      !(build.pull_request.labels includes "Run Wasm tests")
    command: |
      nix develop .#wasm --print-build-logs --command make -f Makefile.wasm32 update
      nix develop .#wasm --print-build-logs --command make -f Makefile.wasm32 frontend-prod

  - label: ":haskell: :macos: Primer Wasm build"
    if: |
      build.branch !~ /^gh-readonly-queue\// &&
      !(build.pull_request.labels includes "Run Wasm tests")
    command: |
      nix develop --no-sandbox .#wasm --print-build-logs --command make -f Makefile.wasm32 update
      nix develop --no-sandbox .#wasm --print-build-logs --command make -f Makefile.wasm32 frontend-prod
    agents:
      os: "darwin"
