agents:
  queue: "cachix-push"
  os: "linux"

env:
  CACHIX_CACHE_NAME: hackworthltd

steps:
  - label: ":nixos: Archive Nix flake inputs to public cache"
    command: nix run github:hackworthltd/hacknix#cachix-archive-flake-inputs .# $CACHIX_CACHE_NAME

  - label: ":nixos: Push project to public cache"
    command: nix run github:hackworthltd/hacknix#cachix-push-attr ciJobs $CACHIX_CACHE_NAME

  - wait

  - label: ":nixos: :linux: Cache Nix shell to public cache"
    command: nix run github:hackworthltd/hacknix#cachix-push-flake-dev-shell primer-dev-shell $CACHIX_CACHE_NAME

  - label: ":nixos: :macos: Cache Nix shell to public cache"
    command: nix run github:hackworthltd/hacknix#cachix-push-flake-dev-shell primer-dev-shell $CACHIX_CACHE_NAME
    agents:
      os: "darwin"
