agents:
  public: "true"
  os: "linux"

env:
  CACHIX_CACHE_NAME: hackworthltd
  CACHIX_CONFIG_PATH: /var/lib/cachix/hackworthltd/cachix.dhall

steps:
  - label: ":nixos: Archive Nix flake inputs to public cache"
    command: nix run github:hackworthltd/hacknix#cachix-archive-flake-inputs .# $CACHIX_CONFIG_PATH $CACHIX_CACHE_NAME

  - label: ":nixos: Push project to public cache"
    command: nix run github:hackworthltd/hacknix#cachix-push-attr ciJobs $CACHIX_CONFIG_PATH $CACHIX_CACHE_NAME
    # Limit to 1 such job at a time because this could be very
    # bandwidth-intensive, and sustained.
    concurrency: 1
    concurrency_group: "primer-cachix-push"

  - wait

  - label: ":nixos: :linux: Cache Nix shell to public cache"
    command: nix run github:hackworthltd/hacknix#cachix-push-flake-dev-shell primer-dev-shell $CACHIX_CONFIG_PATH $CACHIX_CACHE_NAME

  - label: ":nixos: :macos: Cache Nix shell to public cache"
    command: nix run github:hackworthltd/hacknix#cachix-push-flake-dev-shell primer-dev-shell $CACHIX_CONFIG_PATH $CACHIX_CACHE_NAME
    agents:
      os: "darwin"
