# NOTE:
#
# Most commands assume you're running this from the top-level `nix
# develop` shell.

build:
	cabal build

configure:
	cabal configure

check:	test

test:
	cabal test

docs:
	cabal haddock

clean:
	cabal clean

realclean:

deps:

.PHONY: build configure test docs clean realclean deps
