# NOTE:
#
# This Makefile assumes you're using the `nix develop .#wasm` shell.

CABAL = wasm32-wasi-cabal

build:
	$(CABAL) build

frontend: build
	./build-frontend.sh

frontend-prod: build
	./build-frontend.sh -Oz

serve-frontend: frontend
	simple-http-server -i -p 8000 -- dist

repl:
	wasm32-wasi-cabal repl exe:primer-miso -finteractive --repl-options='-fghci-browser -fghci-browser-port=8080'

clean:
	$(CABAL) clean
	rm -rf dist/

.PHONY: build clean
