name: Update Nix dependencies

on:
  schedule:
    # 3 am every Saturday.
    - cron: '0 3 * * 6'

jobs:
  update-nix-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v16
    - run: nix flake update
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.0.1
      with:
        commit-message: "chore(nix): update dependencies"
        title: "chore(nix): update dependencies"
        branch: "chore/update-nix-dependencies"
