name: Update Nix dependencies.

on:
  workflow_dispatch:
  schedule:
    # 3 am every Saturday.
    - cron: '0 3 * * 6'

jobs:
  update-nix-dependencies:
    uses: hackworthltd/.github/.github/workflows/reusable-update-nix-flake-public.yml@main
